server {
    listen 80;
    server_name www.legoumarket.cloud;

    root /var/www;
    autoindex off;

    location /gameaistudio/ {
        try_files $uri =404;
        add_header X-Content-Type-Options nosniff always;
    }
}
